/**
 * Part A — Exact full App vs siteDiag=effects delta.
 * Items present in the real production/full App path but absent from the
 * stable diagnostic effects shell.
 *
 * Columns:
 * file | mountedOnHomepage | startsBeforeUserInteraction | longLivedResource | cleanup | introducedOrChangedDuringBeyond | risk
 */

/** @typedef {{
 *   subsystem: string,
 *   file: string,
 *   mountedOnHomepage: boolean | "on-demand",
 *   startsBeforeUserInteraction: boolean,
 *   longLivedResource: string,
 *   cleanup: string,
 *   introducedOrChangedDuringBeyond: boolean | "partial",
 *   risk: "high" | "medium" | "low" | "none",
 *   notes?: string,
 * }} FullVsEffectsRow
 */

/** @type {ReadonlyArray<FullVsEffectsRow>} */
export const FULL_VS_EFFECTS_DELTA = Object.freeze([
  {
    subsystem: "Portfolio Assistant + preview interval",
    file: "src/App.jsx (PortfolioAssistant)",
    mountedOnHomepage: true,
    startsBeforeUserInteraction: true,
    longLivedResource: "setInterval 3600ms; custom event listeners on activate",
    cleanup: "clearInterval / removeEventListener on unmount",
    introducedOrChangedDuringBeyond: false,
    risk: "medium",
  },
  {
    subsystem: "Portfolio intro / splash + sessionStorage",
    file: "src/App.jsx (PortfolioIntro)",
    mountedOnHomepage: "on-demand",
    startsBeforeUserInteraction: true,
    longLivedResource: "setTimeout chain ~3.8s; sessionStorage portfolioIntroSeen",
    cleanup: "clearTimeout on unmount",
    introducedOrChangedDuringBeyond: "partial",
    risk: "low",
    notes: "Beyond deep-link skips intro; intro itself predates Beyond",
  },
  {
    subsystem: "Beyond entry button (ARGovernanceCard)",
    file: "src/components/ar/ARGovernanceCard.jsx via beyondBundle",
    mountedOnHomepage: true,
    startsBeforeUserInteraction: true,
    longLivedResource: "DOM button only (no camera)",
    cleanup: "unmount",
    introducedOrChangedDuringBeyond: true,
    risk: "low",
  },
  {
    subsystem: "Beyond view host (ARGovernanceView only while open)",
    file: "src/components/ar/ARGovernanceView.jsx",
    mountedOnHomepage: false,
    startsBeforeUserInteraction: false,
    longLivedResource: "none while closed; AR session while open",
    cleanup: "unmount on close + adapter dispose",
    introducedOrChangedDuringBeyond: true,
    risk: "medium",
    notes: "Step 6.4: not mounted or imported while Beyond is closed",
  },
  {
    subsystem: "Beyond query / deep-link parsing",
    file: "src/components/ar/beyondCvDeepLink.js",
    mountedOnHomepage: true,
    startsBeforeUserInteraction: true,
    longLivedResource: "reads location.search/hash on App init",
    cleanup: "n/a",
    introducedOrChangedDuringBeyond: true,
    risk: "low",
  },
  {
    subsystem: "AR runtime flags latch (global)",
    file: "src/components/ar/arRuntimeFlags.js via main.jsx",
    mountedOnHomepage: true,
    startsBeforeUserInteraction: true,
    longLivedResource: "session-latched URL flags object",
    cleanup: "tab lifetime",
    introducedOrChangedDuringBeyond: true,
    risk: "low",
  },
  {
    subsystem: "Build id publish (global)",
    file: "src/components/ar/arBuildId.js via main.jsx",
    mountedOnHomepage: true,
    startsBeforeUserInteraction: true,
    longLivedResource: "window + meta portfolio-build-id",
    cleanup: "tab lifetime",
    introducedOrChangedDuringBeyond: true,
    risk: "low",
  },
  {
    subsystem: "Eager AR module graph in initial JS",
    file: "beyondBundle (light) + App lazy ARGovernanceView on open",
    mountedOnHomepage: false,
    startsBeforeUserInteraction: false,
    longLivedResource: "Card + deep-link only while closed; View/adapter async on open",
    cleanup: "n/a while closed",
    introducedOrChangedDuringBeyond: true,
    risk: "low",
    notes: "Step 6.4: beyondBundle no longer exports ARGovernanceView",
  },
  {
    subsystem: "MindAR / TensorFlow / Three package load",
    file: "MindARTrackingAdapter dynamic import()",
    mountedOnHomepage: false,
    startsBeforeUserInteraction: false,
    longLivedResource: "worker + WASM/TF + WebGL on camera start only",
    cleanup: "adapter stop / Patch AB dispose",
    introducedOrChangedDuringBeyond: true,
    risk: "high",
    notes: "NOT required for idle homepage crash (camera closed)",
  },
  {
    subsystem: ".mind target / GLB asset fetch",
    file: "checkArTargetAvailable / loadInterestGlb",
    mountedOnHomepage: false,
    startsBeforeUserInteraction: false,
    longLivedResource: "network + decoded buffers after Beyond activate",
    cleanup: "session dispose",
    introducedOrChangedDuringBeyond: true,
    risk: "medium",
    notes: "paths are embedded in initial JS; fetch waits for open/camera",
  },
  {
    subsystem: "AR portal host under documentElement",
    file: "src/components/ar/arViewport.js ensureArPortalHost",
    mountedOnHomepage: "on-demand",
    startsBeforeUserInteraction: false,
    longLivedResource: "DOM portal host + shell when open",
    cleanup: "teardownArPortalHost on close",
    introducedOrChangedDuringBeyond: true,
    risk: "medium",
  },
  {
    subsystem: "visualViewport / resize / orientation listeners",
    file: "src/components/ar/arViewport.js bindArViewportListeners",
    mountedOnHomepage: "on-demand",
    startsBeforeUserInteraction: false,
    longLivedResource: "resize + orientationchange + visualViewport resize/scroll",
    cleanup: "unbind on portal close",
    introducedOrChangedDuringBeyond: true,
    risk: "medium",
  },
  {
    subsystem: "Scroll / page lock + portfolio inert",
    file: "src/components/ar/arPageLock.js",
    mountedOnHomepage: "on-demand",
    startsBeforeUserInteraction: false,
    longLivedResource: "document/body style mutations while AR open",
    cleanup: "unlock on close",
    introducedOrChangedDuringBeyond: true,
    risk: "medium",
  },
  {
    subsystem: "ARTrackingErrorBoundary",
    file: "src/components/ar/ARTrackingErrorBoundary.jsx",
    mountedOnHomepage: "on-demand",
    startsBeforeUserInteraction: false,
    longLivedResource: "error boundary around camera tree only",
    cleanup: "unmount",
    introducedOrChangedDuringBeyond: true,
    risk: "low",
    notes: "No silent homepage redirect found",
  },
  {
    subsystem: "Real portfolio sections (capabilities/projects/radar/education)",
    file: "src/App.jsx",
    mountedOnHomepage: true,
    startsBeforeUserInteraction: true,
    longLivedResource: "shared ticker scheduler (≤1 rAF), radar sweep only in-view, CSS glows (static on iOS)",
    cleanup: "effect cleanups / unmount / offscreen pause",
    introducedOrChangedDuringBeyond: false,
    risk: "medium",
    notes: "Step 6.4 ownership + iOS stability; still the primary idle content surface",
  },
  {
    subsystem: "ProjectDeck assistant:activate-project listener",
    file: "src/App.jsx (ProjectDeck)",
    mountedOnHomepage: true,
    startsBeforeUserInteraction: true,
    longLivedResource: "window custom event listener",
    cleanup: "removeEventListener",
    introducedOrChangedDuringBeyond: false,
    risk: "low",
  },
  {
    subsystem: "AcademicFocusInfo resize/scroll listeners",
    file: "src/App.jsx (AcademicFocusInfo)",
    mountedOnHomepage: "on-demand",
    startsBeforeUserInteraction: false,
    longLivedResource: "resize + scroll capture while tooltip open",
    cleanup: "remove when closed",
    introducedOrChangedDuringBeyond: false,
    risk: "low",
  },
  {
    subsystem: "index.css AR viewport / portal rules",
    file: "src/index.css",
    mountedOnHomepage: true,
    startsBeforeUserInteraction: true,
    longLivedResource: "CSS parsed globally (ar-portal-host, ar-viewport-shell, lens glow)",
    cleanup: "n/a",
    introducedOrChangedDuringBeyond: "partial",
    risk: "low",
  },
  {
    subsystem: "Service worker / forced reload",
    file: "— (none in repo)",
    mountedOnHomepage: false,
    startsBeforeUserInteraction: false,
    longLivedResource: "none",
    cleanup: "n/a",
    introducedOrChangedDuringBeyond: false,
    risk: "none",
  },
  {
    subsystem: "HTML preload/prefetch of .mind/GLB",
    file: "index.html",
    mountedOnHomepage: false,
    startsBeforeUserInteraction: false,
    longLivedResource: "no asset prefetch links; Vite may modulepreload JS chunks",
    cleanup: "n/a",
    introducedOrChangedDuringBeyond: "partial",
    risk: "low",
  },
]);

export function getFullVsEffectsDeltaMatrix() {
  return FULL_VS_EFFECTS_DELTA.map((row) => ({
    subsystem: row.subsystem,
    file: row.file,
    mountedOnHomepage: String(row.mountedOnHomepage),
    startsBeforeUserInteraction: String(row.startsBeforeUserInteraction),
    longLivedResource: row.longLivedResource,
    cleanup: row.cleanup,
    introducedOrChangedDuringBeyond: String(row.introducedOrChangedDuringBeyond),
    risk: row.risk,
  }));
}
